//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamBook.Application.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DreamBook.Application.Resources.ExceptionMessages.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В книге {0} уже есть толкование для {1}..
        /// </summary>
        public static string BookAlreadyHasInterpretationForWord {
            get {
                return ResourceManager.GetString("BookAlreadyHasInterpretationForWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to он содержит толкование нескольких слов.
        /// </summary>
        public static string BookCanNotBeDeletedReason {
            get {
                return ResourceManager.GetString("BookCanNotBeDeletedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Книга с названием &apos;{0}&apos; уже существует..
        /// </summary>
        public static string BookWithSameNameExist {
            get {
                return ResourceManager.GetString("BookWithSameNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория &quot;{0}&quot; уже существует..
        /// </summary>
        public static string CategoryWithSameNameExist {
            get {
                return ResourceManager.GetString("CategoryWithSameNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип &apos;{0}&apos; уже существует..
        /// </summary>
        public static string DreamTypeWithSameNameExist {
            get {
                return ResourceManager.GetString("DreamTypeWithSameNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to он используется в нескольких снах.
        /// </summary>
        public static string DreatemTypeCanNotBeDeletedReason {
            get {
                return ResourceManager.GetString("DreatemTypeCanNotBeDeletedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ({1}) не может быть удален, потому что, {2}..
        /// </summary>
        public static string EntityCanNotBeDeleted {
            get {
                return ResourceManager.GetString("EntityCanNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} с {1} не существует..
        /// </summary>
        public static string EntityNotFound {
            get {
                return ResourceManager.GetString("EntityNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} не был создан по неизвестной причине..
        /// </summary>
        public static string EntityWasNotSavedToDB {
            get {
                return ResourceManager.GetString("EntityWasNotSavedToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Внутренняя Ошибка Сервера..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to есть несколько постов с этой категорией.
        /// </summary>
        public static string PostCategoryCanNotBeDeletedReason {
            get {
                return ResourceManager.GetString("PostCategoryCanNotBeDeletedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Учетная запись пользователя не может быть удалена. Только владелец может удалить эту учетную запись..
        /// </summary>
        public static string UserCannotBeDeleted {
            get {
                return ResourceManager.GetString("UserCannotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} уже используется другим пользователем..
        /// </summary>
        public static string UserWithTheSameEmailAlreadyExist {
            get {
                return ResourceManager.GetString("UserWithTheSameEmailAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь с ником &apos;{0}&apos; уже существует..
        /// </summary>
        public static string UserWithTheSameUserNameAlreadyExist {
            get {
                return ResourceManager.GetString("UserWithTheSameUserNameAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла одна или несколько ошибок проверки!.
        /// </summary>
        public static string ValidationErrorOccurred {
            get {
                return ResourceManager.GetString("ValidationErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to он используется в нескольких снах.
        /// </summary>
        public static string WordCanNotBeDeletedReason {
            get {
                return ResourceManager.GetString("WordCanNotBeDeletedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово &quot;{0}&quot; уже существует..
        /// </summary>
        public static string WordWithSameNameExist {
            get {
                return ResourceManager.GetString("WordWithSameNameExist", resourceCulture);
            }
        }
    }
}
