//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamBook.Application.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DreamBook.Application.Resources.ExceptionMessages.ExceptionMessages", typeof(ExceptionMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it is used on several dreams.
        /// </summary>
        public static string DreatemTypeCanNotBeDeletedReason {
            get {
                return ResourceManager.GetString("DreatemTypeCanNotBeDeletedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:EntityName} ({1:EntityId}) cannot be deleted because {2:Reason}..
        /// </summary>
        public static string EntityCanNotBeDeleted {
            get {
                return ResourceManager.GetString("EntityCanNotBeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:EntityName} was not created with an unknown reason..
        /// </summary>
        public static string EntityWasNotSavedToDB {
            get {
                return ResourceManager.GetString("EntityWasNotSavedToDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to it is used on several dreams.
        /// </summary>
        public static string InterpretationCanNotBeDeletedReason {
            get {
                return ResourceManager.GetString("InterpretationCanNotBeDeletedReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language with &quot;{0:laguage}&quot; id does not exist..
        /// </summary>
        public static string LanguageNotFound {
            get {
                return ResourceManager.GetString("LanguageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to there are several post this this category.
        /// </summary>
        public static string PostCategoryCanNotBeDeletedReason {
            get {
                return ResourceManager.GetString("PostCategoryCanNotBeDeletedReason", resourceCulture);
            }
        }
    }
}
