//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DreamBook.Application.LanguageResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ModelsLabel {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelsLabel() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DreamBook.Application.Resources.Model.ModelsLabel", typeof(ModelsLabel).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реклама.
        /// </summary>
        public static string Ad {
            get {
                return ResourceManager.GetString("Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        public static string Ad_DateTime {
            get {
                return ResourceManager.GetString("Ad_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Ad_Image {
            get {
                return ResourceManager.GetString("Ad_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активный.
        /// </summary>
        public static string Ad_IsActive {
            get {
                return ResourceManager.GetString("Ad_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Источник.
        /// </summary>
        public static string Ad_Source {
            get {
                return ResourceManager.GetString("Ad_Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string Ad_Translations {
            get {
                return ResourceManager.GetString("Ad_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод рекламы.
        /// </summary>
        public static string AdTranslation {
            get {
                return ResourceManager.GetString("AdTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Реклама.
        /// </summary>
        public static string AdTranslation_Ad {
            get {
                return ResourceManager.GetString("AdTranslation_Ad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string AdTranslation_Description {
            get {
                return ResourceManager.GetString("AdTranslation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string AdTranslation_Language {
            get {
                return ResourceManager.GetString("AdTranslation_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string AdTranslation_Title {
            get {
                return ResourceManager.GetString("AdTranslation_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        public static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Book_Description {
            get {
                return ResourceManager.GetString("Book_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Book_Language {
            get {
                return ResourceManager.GetString("Book_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Book_Name {
            get {
                return ResourceManager.GetString("Book_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string Book_Translations {
            get {
                return ResourceManager.GetString("Book_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Мечтать.
        /// </summary>
        public static string Dream {
            get {
                return ResourceManager.GetString("Dream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделится.
        /// </summary>
        public static string Dream_CanBeShared {
            get {
                return ResourceManager.GetString("Dream_CanBeShared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата время.
        /// </summary>
        public static string Dream_DateTime {
            get {
                return ResourceManager.GetString("Dream_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string Dream_Description {
            get {
                return ResourceManager.GetString("Dream_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Dream_Image {
            get {
                return ResourceManager.GetString("Dream_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сонник.
        /// </summary>
        public static string Dream_Interpretations {
            get {
                return ResourceManager.GetString("Dream_Interpretations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Местоположение.
        /// </summary>
        public static string Dream_Location {
            get {
                return ResourceManager.GetString("Dream_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество просмотров.
        /// </summary>
        public static string Dream_NumberOfViews {
            get {
                return ResourceManager.GetString("Dream_NumberOfViews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Dream_Title {
            get {
                return ResourceManager.GetString("Dream_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string Dream_Type {
            get {
                return ResourceManager.GetString("Dream_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string Dream_User {
            get {
                return ResourceManager.GetString("Dream_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Погода.
        /// </summary>
        public static string Dream_Weather {
            get {
                return ResourceManager.GetString("Dream_Weather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сонник сна.
        /// </summary>
        public static string DreamInterpretation {
            get {
                return ResourceManager.GetString("DreamInterpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сон.
        /// </summary>
        public static string DreamInterpretation_Dream {
            get {
                return ResourceManager.GetString("DreamInterpretation_Dream", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сонник.
        /// </summary>
        public static string DreamInterpretation_Interpretation {
            get {
                return ResourceManager.GetString("DreamInterpretation_Interpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип сна.
        /// </summary>
        public static string DreamType {
            get {
                return ResourceManager.GetString("DreamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цвет.
        /// </summary>
        public static string DreamType_Color {
            get {
                return ResourceManager.GetString("DreamType_Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сны.
        /// </summary>
        public static string DreamType_Dreams {
            get {
                return ResourceManager.GetString("DreamType_Dreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string DreamType_Translations {
            get {
                return ResourceManager.GetString("DreamType_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод типа сна.
        /// </summary>
        public static string DreamTypeTranslation {
            get {
                return ResourceManager.GetString("DreamTypeTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string DreamTypeTranslation_Description {
            get {
                return ResourceManager.GetString("DreamTypeTranslation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тип.
        /// </summary>
        public static string DreamTypeTranslation_DreamType {
            get {
                return ResourceManager.GetString("DreamTypeTranslation_DreamType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string DreamTypeTranslation_Language {
            get {
                return ResourceManager.GetString("DreamTypeTranslation_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string DreamTypeTranslation_Name {
            get {
                return ResourceManager.GetString("DreamTypeTranslation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идентификатор.
        /// </summary>
        public static string Entity_Guid {
            get {
                return ResourceManager.GetString("Entity_Guid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сонник.
        /// </summary>
        public static string Interpretation {
            get {
                return ResourceManager.GetString("Interpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сны.
        /// </summary>
        public static string Interpretation_Dreams {
            get {
                return ResourceManager.GetString("Interpretation_Dreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string Interpretation_Translations {
            get {
                return ResourceManager.GetString("Interpretation_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод сонника.
        /// </summary>
        public static string InterpretationTranslation {
            get {
                return ResourceManager.GetString("InterpretationTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string InterpretationTranslation_Description {
            get {
                return ResourceManager.GetString("InterpretationTranslation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сонник.
        /// </summary>
        public static string InterpretationTranslation_Interpretation {
            get {
                return ResourceManager.GetString("InterpretationTranslation_Interpretation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string InterpretationTranslation_Language {
            get {
                return ResourceManager.GetString("InterpretationTranslation_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string InterpretationTranslation_Name {
            get {
                return ResourceManager.GetString("InterpretationTranslation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Краткое описание.
        /// </summary>
        public static string InterpretationTranslation_ShortDescription {
            get {
                return ResourceManager.GetString("InterpretationTranslation_ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Код языка.
        /// </summary>
        public static string Language_Code {
            get {
                return ResourceManager.GetString("Language_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Language_Name {
            get {
                return ResourceManager.GetString("Language_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Почта.
        /// </summary>
        public static string Post {
            get {
                return ResourceManager.GetString("Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string Post_Category {
            get {
                return ResourceManager.GetString("Post_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cодержание.
        /// </summary>
        public static string Post_Content {
            get {
                return ResourceManager.GetString("Post_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата и время.
        /// </summary>
        public static string Post_DateTime {
            get {
                return ResourceManager.GetString("Post_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изображение.
        /// </summary>
        public static string Post_Image {
            get {
                return ResourceManager.GetString("Post_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Активный.
        /// </summary>
        public static string Post_IsActive {
            get {
                return ResourceManager.GetString("Post_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Заголовок.
        /// </summary>
        public static string Post_Title {
            get {
                return ResourceManager.GetString("Post_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория публикации.
        /// </summary>
        public static string PostCategory {
            get {
                return ResourceManager.GetString("PostCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Публикации.
        /// </summary>
        public static string PostCategory_Posts {
            get {
                return ResourceManager.GetString("PostCategory_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string PostCategory_Translations {
            get {
                return ResourceManager.GetString("PostCategory_Translations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевод категории публикаций.
        /// </summary>
        public static string PostCategoryTranslation {
            get {
                return ResourceManager.GetString("PostCategoryTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Категория.
        /// </summary>
        public static string PostCategoryTranslation_Category {
            get {
                return ResourceManager.GetString("PostCategoryTranslation_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Описание.
        /// </summary>
        public static string PostCategoryTranslation_Description {
            get {
                return ResourceManager.GetString("PostCategoryTranslation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string PostCategoryTranslation_Language {
            get {
                return ResourceManager.GetString("PostCategoryTranslation_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string PostCategoryTranslation_Name {
            get {
                return ResourceManager.GetString("PostCategoryTranslation_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to День рождения.
        /// </summary>
        public static string User_Birthday {
            get {
                return ResourceManager.GetString("User_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сны.
        /// </summary>
        public static string User_Dreams {
            get {
                return ResourceManager.GetString("User_Dreams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Электронная почта.
        /// </summary>
        public static string User_Email {
            get {
                return ResourceManager.GetString("User_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пол.
        /// </summary>
        public static string User_Gender {
            get {
                return ResourceManager.GetString("User_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя.
        /// </summary>
        public static string User_Name {
            get {
                return ResourceManager.GetString("User_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Имя пользователя.
        /// </summary>
        public static string User_Username {
            get {
                return ResourceManager.GetString("User_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Слово.
        /// </summary>
        public static string Word {
            get {
                return ResourceManager.GetString("Word", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Толкование.
        /// </summary>
        public static string Word_Interpretations {
            get {
                return ResourceManager.GetString("Word_Interpretations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Название.
        /// </summary>
        public static string Word_Name {
            get {
                return ResourceManager.GetString("Word_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переводы.
        /// </summary>
        public static string Word_Translations {
            get {
                return ResourceManager.GetString("Word_Translations", resourceCulture);
            }
        }
    }
}
